apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - name: library-app
          image: library-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: library-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  selector:
    app: library-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: library-app-config
data:
  APP_ENV: "dev"
  DATABASE_URL: "jdbc:h2:mem:librarydb"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: library-app-service
                port:
                  number: 80
